'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductID As Integer
    Public Property Name As String
    Public Property ProductNumber As String
    Public Property MakeFlag As Boolean
    Public Property FinishedGoodsFlag As Boolean
    Public Property Color As String
    Public Property SafetyStockLevel As Short
    Public Property ReorderPoint As Short
    Public Property StandardCost As Decimal
    Public Property ListPrice As Decimal
    Public Property Size As String
    Public Property SizeUnitMeasureCode As String
    Public Property WeightUnitMeasureCode As String
    Public Property Weight As Nullable(Of Decimal)
    Public Property DaysToManufacture As Integer
    Public Property ProductLine As String
    Public Property [Class] As String
    Public Property Style As String
    Public Property ProductSubcategoryID As Nullable(Of Integer)
    Public Property ProductModelID As Nullable(Of Integer)
    Public Property SellStartDate As Date
    Public Property SellEndDate As Nullable(Of Date)
    Public Property DiscontinuedDate As Nullable(Of Date)
    Public Property rowguid As System.Guid
    Public Property ModifiedDate As Date

    Public Overridable Property ProductSubcategory As ProductSubcategory

End Class
